version: "3.8"
services:
  jupyter:
    build:
      context: .
      dockerfile: jupyter/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/app
    env_file:
      - .env
  langserve:
    build:
      context: .
      dockerfile: langserve/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env